title: ブログのタイトル
description: ブログの説明文
twitter: example
github: example
website: http://example.com
email: email@example.com
num_posts_on_index: 3
writer_name: Jane Doe
host_name: blog.example.com
google_analytics: UA-XXXXXXXX-1
permalink: /posts/:title