title: ブログのタイトル
description: ブログの説明文
permalink: /posts/:title
markdown: redcarpet

# Used by liquid
settings:
  num_posts_on_index: 3
  host_name: blog.example.com
author:
  name: Jane Doe
  twitter: example
  github: example
  website: http://example.com
  email: email@example.com
code:
  google_analytics: UA-XXXXXXXX-1