title: Elle Kasai
description: 笠井枝理依のブログ｡UIデザイナーを目指して奮闘中!
permalink: /posts/:title
markdown: redcarpet

# Used by liquid
settings:
  num_posts_on_index: 3
  host_name: ellekasai.com
  comments: true
  optional:
    license: https://github.com/ellekasai/ellekasai.com/blob/gh-pages/README.md
author:
  name: Elle Kasai
  twitter: Krizel77
  github: ellekasai
  website: about.me/elle_kasai
  email: elle.kasai@gmail.com
  about: 88年七夕生まれ。決済系のITベンチャーで法人営業として働いていたが､この春に退職｡現在はUIデザイナーに転身するべく勉強中。素材写真モデルとしても活動している｡学習院女子大学国際文化交流学部の出身｡趣味は読書と映画鑑賞、特技は朗読やアナウンスといった放送系。
  optional:
    gplus: https://plus.google.com/110578585985399309952
    photo: http://f.cl.ly/items/0g3r41202a2E3k3I0A3s/elle450.jpeg
code:
  google_analytics: UA-36051690-2
  fb_admins: 1214763701
